[package]
name = "championship-soccer-editor"
version = "0.1.0"
edition = "2024"
publish = false
description = "World editor per Championship Soccer"

[dependencies]
eframe = { version = "0.36.2", default-features = false, features = ["default_fonts", "glow", "persistence"] }
rfd = { version = "0.17.2", default-features = false }
encoding_rs = "0.8.41"
